### ISSUE TITLE
depends-on plot/vglt system not found

### ISSUE THREAD

**Issue by metadatadriven** [Lisp-Stat/IPS#1]
I have a new install of Portacle on Windows, and ` (ql:quickload :ips)` is failing with the following condition:

```
System "plot/vglt" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
```

I cannot see a :plot/vglt package anywhere? Quicklist has a vgplot package but this does not export plot/vglt

What am I missing?

Thanks!

**Comment by metadatadriven** [comment]
Ah! got it working.. had to install the plot package using instructions in the following section:

https://lisp-stat.dev/docs/getting-started/#manual-install

**Comment by Symbolics** [comment]
Thank you for the report. I have requested that `plot` be [added to quicklisp](https://github.com/quicklisp/quicklisp-projects/issues/2029). After this is done, the install will be automatic.

I'll close this now. If you have other problems (or suggestions/comments), please open a new issue. I'm through the pie chart now and starting on stem-and-leaf, in case you need those.
