### ISSUE TITLE
How to load the COUPON file

### ISSUE THREAD

**Issue by foretspaisibles** [Lisp-Stat/IPS#3]
The notebook has some indication that data used comes from IPS9 book. Visiting the website of the book it is not evident where to find the coupon file.

Also my Lisp (SBCL) does not automatically apply `translate-logical-pathnames` to `load` arguments, so I probably need to `(load (translate-logical-pathname "IPS:DATA;coupons"))`.

**Comment by snunez1** [comment]
The coupon file is included in the data/ directory of the IPS system.  This should all be taken care of automatically.  What happens when you `(load #P"IPS:DATA;coupons")`?  It is case sensitive.

**Comment by foretspaisibles** [comment]
The data directory does not seem to be in the `master` branch of the repository.

This is my remote repo (this repo):
```
➜  IPS9 git:(master) git remote -v         
origin	git@github.com:Lisp-Stat/IPS9.git (fetch)
origin	git@github.com:Lisp-Stat/IPS9.git (push)
```

The working copy contains the definition of IPS:
```
➜  IPS9 git:(master) grep defsystem ips.asd
(defsystem #:ips
```

There is no data folder:
```
➜  IPS9 git:(master) ls data
ls: data: No such file or directory
```

My working copy is clean:
```
➜  IPS9 git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```


Thank you for the quick response and for your work on LispStat!

**Comment by snunez1** [comment]
Opps.  That was a bug, thanks.  Now fixed.

**Comment by foretspaisibles** [comment]
Great, thanks! :-)
